version: '3.8'
services:
  app:
    build: ./docker
    ports:
      - "8080:80"
    volumes:
      - ../public:/var/www/html
      - ../src:/var/www/html/src
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: xerpia
      MYSQL_USER: xerpia
      MYSQL_PASSWORD: xerpia123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
